using System.Drawing;

namespace MaterialComponents
{
    /// <summary>
    /// A Material 3 color family (color / onColor / container / onContainer),
    /// mirroring the ColorFamily class generated by the Material Theme Builder.
    /// </summary>
    public sealed class LMaterialColorFamily
    {
        public Color Color { get; private set; }
        public Color OnColor { get; private set; }
        public Color ColorContainer { get; private set; }
        public Color OnColorContainer { get; private set; }

        public LMaterialColorFamily(Color color, Color onColor, Color container, Color onContainer)
        {
            Color = color;
            OnColor = onColor;
            ColorContainer = container;
            OnColorContainer = onContainer;
        }
    }

    /// <summary>
    /// Full Material 3 color scheme, ported 1:1 from the Jetpack Compose
    /// theme in _material_expressive_theme/Color.kt.
    /// </summary>
    public sealed class LMaterialColorScheme
    {
        public bool IsDark { get; private set; }

        public Color Primary { get; set; }
        public Color OnPrimary { get; set; }
        public Color PrimaryContainer { get; set; }
        public Color OnPrimaryContainer { get; set; }
        public Color Secondary { get; set; }
        public Color OnSecondary { get; set; }
        public Color SecondaryContainer { get; set; }
        public Color OnSecondaryContainer { get; set; }
        public Color Tertiary { get; set; }
        public Color OnTertiary { get; set; }
        public Color TertiaryContainer { get; set; }
        public Color OnTertiaryContainer { get; set; }
        public Color Error { get; set; }
        public Color OnError { get; set; }
        public Color ErrorContainer { get; set; }
        public Color OnErrorContainer { get; set; }
        public Color Background { get; set; }
        public Color OnBackground { get; set; }
        public Color Surface { get; set; }
        public Color OnSurface { get; set; }
        public Color SurfaceVariant { get; set; }
        public Color OnSurfaceVariant { get; set; }
        public Color Outline { get; set; }
        public Color OutlineVariant { get; set; }
        public Color Scrim { get; set; }
        public Color Shadow { get; set; }
        public Color InverseSurface { get; set; }
        public Color InverseOnSurface { get; set; }
        public Color InversePrimary { get; set; }
        public Color SurfaceDim { get; set; }
        public Color SurfaceBright { get; set; }
        public Color SurfaceContainerLowest { get; set; }
        public Color SurfaceContainerLow { get; set; }
        public Color SurfaceContainer { get; set; }
        public Color SurfaceContainerHigh { get; set; }
        public Color SurfaceContainerHighest { get; set; }

        public LMaterialColorFamily CustomColor1 { get; set; }
        public LMaterialColorFamily CustomColor2 { get; set; }

        private LMaterialColorScheme(bool isDark) { IsDark = isDark; }

        private static Color C(uint argb) { return Color.FromArgb(unchecked((int)argb)); }

        public static readonly LMaterialColorScheme Light = new LMaterialColorScheme(false)
        {
            Primary = C(0xFF8C4F27), OnPrimary = C(0xFFFFFFFF), PrimaryContainer = C(0xFFFFDBC8), OnPrimaryContainer = C(0xFF6F3811),
            Secondary = C(0xFF765847), OnSecondary = C(0xFFFFFFFF), SecondaryContainer = C(0xFFFFDBC8), OnSecondaryContainer = C(0xFF5C4131),
            Tertiary = C(0xFF626033), OnTertiary = C(0xFFFFFFFF), TertiaryContainer = C(0xFFE8E5AC), OnTertiaryContainer = C(0xFF4A491E),
            Error = C(0xFFBA1A1A), OnError = C(0xFFFFFFFF), ErrorContainer = C(0xFFFFDAD6), OnErrorContainer = C(0xFF93000A),
            Background = C(0xFFFFF8F5), OnBackground = C(0xFF221A15), Surface = C(0xFFFFF8F5), OnSurface = C(0xFF221A15),
            SurfaceVariant = C(0xFFF4DED3), OnSurfaceVariant = C(0xFF52443C), Outline = C(0xFF85746B), OutlineVariant = C(0xFFD7C2B8),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFF382E29), InverseOnSurface = C(0xFFFFEDE5), InversePrimary = C(0xFFFFB68B),
            SurfaceDim = C(0xFFE7D7CF), SurfaceBright = C(0xFFFFF8F5),
            SurfaceContainerLowest = C(0xFFFFFFFF), SurfaceContainerLow = C(0xFFFFF1EA), SurfaceContainer = C(0xFFFCEAE2),
            SurfaceContainerHigh = C(0xFFF6E5DD), SurfaceContainerHighest = C(0xFFF0DFD7),
            CustomColor1 = new LMaterialColorFamily(C(0xFF79590C), C(0xFFFFFFFF), C(0xFFFFDEA2), C(0xFF5C4200)),
            CustomColor2 = new LMaterialColorFamily(C(0xFF4E662A), C(0xFFFFFFFF), C(0xFFCFEDA1), C(0xFF374E14)),
        };

        public static readonly LMaterialColorScheme LightMediumContrast = new LMaterialColorScheme(false)
        {
            Primary = C(0xFF5A2802), OnPrimary = C(0xFFFFFFFF), PrimaryContainer = C(0xFF9D5D33), OnPrimaryContainer = C(0xFFFFFFFF),
            Secondary = C(0xFF493022), OnSecondary = C(0xFFFFFFFF), SecondaryContainer = C(0xFF866655), OnSecondaryContainer = C(0xFFFFFFFF),
            Tertiary = C(0xFF39380E), OnTertiary = C(0xFFFFFFFF), TertiaryContainer = C(0xFF716F40), OnTertiaryContainer = C(0xFFFFFFFF),
            Error = C(0xFF740006), OnError = C(0xFFFFFFFF), ErrorContainer = C(0xFFCF2C27), OnErrorContainer = C(0xFFFFFFFF),
            Background = C(0xFFFFF8F5), OnBackground = C(0xFF221A15), Surface = C(0xFFFFF8F5), OnSurface = C(0xFF170F0B),
            SurfaceVariant = C(0xFFF4DED3), OnSurfaceVariant = C(0xFF41332C), Outline = C(0xFF5E4F47), OutlineVariant = C(0xFF7A6A61),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFF382E29), InverseOnSurface = C(0xFFFFEDE5), InversePrimary = C(0xFFFFB68B),
            SurfaceDim = C(0xFFD3C3BC), SurfaceBright = C(0xFFFFF8F5),
            SurfaceContainerLowest = C(0xFFFFFFFF), SurfaceContainerLow = C(0xFFFFF1EA), SurfaceContainer = C(0xFFF6E5DD),
            SurfaceContainerHigh = C(0xFFEADAD2), SurfaceContainerHighest = C(0xFFDFCEC7),
            CustomColor1 = new LMaterialColorFamily(C(0xFF473300), C(0xFFFFFFFF), C(0xFF89681C), C(0xFFFFFFFF)),
            CustomColor2 = new LMaterialColorFamily(C(0xFF273C03), C(0xFFFFFFFF), C(0xFF5C7537), C(0xFFFFFFFF)),
        };

        public static readonly LMaterialColorScheme LightHighContrast = new LMaterialColorScheme(false)
        {
            Primary = C(0xFF4C1F00), OnPrimary = C(0xFFFFFFFF), PrimaryContainer = C(0xFF723A13), OnPrimaryContainer = C(0xFFFFFFFF),
            Secondary = C(0xFF3E2718), OnSecondary = C(0xFFFFFFFF), SecondaryContainer = C(0xFF5E4333), OnSecondaryContainer = C(0xFFFFFFFF),
            Tertiary = C(0xFF2E2E05), OnTertiary = C(0xFFFFFFFF), TertiaryContainer = C(0xFF4C4B20), OnTertiaryContainer = C(0xFFFFFFFF),
            Error = C(0xFF600004), OnError = C(0xFFFFFFFF), ErrorContainer = C(0xFF98000A), OnErrorContainer = C(0xFFFFFFFF),
            Background = C(0xFFFFF8F5), OnBackground = C(0xFF221A15), Surface = C(0xFFFFF8F5), OnSurface = C(0xFF000000),
            SurfaceVariant = C(0xFFF4DED3), OnSurfaceVariant = C(0xFF000000), Outline = C(0xFF362923), OutlineVariant = C(0xFF55463E),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFF382E29), InverseOnSurface = C(0xFFFFFFFF), InversePrimary = C(0xFFFFB68B),
            SurfaceDim = C(0xFFC5B6AE), SurfaceBright = C(0xFFFFF8F5),
            SurfaceContainerLowest = C(0xFFFFFFFF), SurfaceContainerLow = C(0xFFFFEDE5), SurfaceContainer = C(0xFFF0DFD7),
            SurfaceContainerHigh = C(0xFFE2D1C9), SurfaceContainerHighest = C(0xFFD3C3BC),
            CustomColor1 = new LMaterialColorFamily(C(0xFF3B2900), C(0xFFFFFFFF), C(0xFF5F4500), C(0xFFFFFFFF)),
            CustomColor2 = new LMaterialColorFamily(C(0xFF1E3200), C(0xFFFFFFFF), C(0xFF395016), C(0xFFFFFFFF)),
        };

        public static readonly LMaterialColorScheme Dark = new LMaterialColorScheme(true)
        {
            Primary = C(0xFFFFB68B), OnPrimary = C(0xFF522300), PrimaryContainer = C(0xFF6F3811), OnPrimaryContainer = C(0xFFFFDBC8),
            Secondary = C(0xFFE5BFAA), OnSecondary = C(0xFF432B1C), SecondaryContainer = C(0xFF5C4131), OnSecondaryContainer = C(0xFFFFDBC8),
            Tertiary = C(0xFFCCC992), OnTertiary = C(0xFF333209), TertiaryContainer = C(0xFF4A491E), OnTertiaryContainer = C(0xFFE8E5AC),
            Error = C(0xFFFFB4AB), OnError = C(0xFF690005), ErrorContainer = C(0xFF93000A), OnErrorContainer = C(0xFFFFDAD6),
            Background = C(0xFF1A120D), OnBackground = C(0xFFF0DFD7), Surface = C(0xFF1A120D), OnSurface = C(0xFFF0DFD7),
            SurfaceVariant = C(0xFF52443C), OnSurfaceVariant = C(0xFFD7C2B8), Outline = C(0xFF9F8D84), OutlineVariant = C(0xFF52443C),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFFF0DFD7), InverseOnSurface = C(0xFF382E29), InversePrimary = C(0xFF8C4F27),
            SurfaceDim = C(0xFF1A120D), SurfaceBright = C(0xFF413732),
            SurfaceContainerLowest = C(0xFF140D08), SurfaceContainerLow = C(0xFF221A15), SurfaceContainer = C(0xFF271E19),
            SurfaceContainerHigh = C(0xFF312823), SurfaceContainerHighest = C(0xFF3D332D),
            CustomColor1 = new LMaterialColorFamily(C(0xFFEBC16C), C(0xFF402D00), C(0xFF5C4200), C(0xFFFFDEA2)),
            CustomColor2 = new LMaterialColorFamily(C(0xFFB4D088), C(0xFF213600), C(0xFF374E14), C(0xFFCFEDA1)),
        };

        public static readonly LMaterialColorScheme DarkMediumContrast = new LMaterialColorScheme(true)
        {
            Primary = C(0xFFFFD3BC), OnPrimary = C(0xFF421A00), PrimaryContainer = C(0xFFC78053), OnPrimaryContainer = C(0xFF000000),
            Secondary = C(0xFFFCD4BE), OnSecondary = C(0xFF372012), SecondaryContainer = C(0xFFAC8A76), OnSecondaryContainer = C(0xFF000000),
            Tertiary = C(0xFFE2DFA6), OnTertiary = C(0xFF282701), TertiaryContainer = C(0xFF959360), OnTertiaryContainer = C(0xFF000000),
            Error = C(0xFFFFD2CC), OnError = C(0xFF540003), ErrorContainer = C(0xFFFF5449), OnErrorContainer = C(0xFF000000),
            Background = C(0xFF1A120D), OnBackground = C(0xFFF0DFD7), Surface = C(0xFF1A120D), OnSurface = C(0xFFFFFFFF),
            SurfaceVariant = C(0xFF52443C), OnSurfaceVariant = C(0xFFEED8CD), Outline = C(0xFFC2AEA4), OutlineVariant = C(0xFF9F8D83),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFFF0DFD7), InverseOnSurface = C(0xFF312823), InversePrimary = C(0xFF703912),
            SurfaceDim = C(0xFF1A120D), SurfaceBright = C(0xFF4D423D),
            SurfaceContainerLowest = C(0xFF0C0604), SurfaceContainerLow = C(0xFF241C17), SurfaceContainer = C(0xFF2F2621),
            SurfaceContainerHigh = C(0xFF3A312B), SurfaceContainerHighest = C(0xFF463B36),
            CustomColor1 = new LMaterialColorFamily(C(0xFFFFD78A), C(0xFF332300), C(0xFFB08B3D), C(0xFF000000)),
            CustomColor2 = new LMaterialColorFamily(C(0xFFC9E69C), C(0xFF192A00), C(0xFF7F9957), C(0xFF000000)),
        };

        public static readonly LMaterialColorScheme DarkHighContrast = new LMaterialColorScheme(true)
        {
            Primary = C(0xFFFFECE3), OnPrimary = C(0xFF000000), PrimaryContainer = C(0xFFFFB182), OnPrimaryContainer = C(0xFF190600),
            Secondary = C(0xFFFFECE3), OnSecondary = C(0xFF000000), SecondaryContainer = C(0xFFE1BBA6), OnSecondaryContainer = C(0xFF180701),
            Tertiary = C(0xFFF6F3B8), OnTertiary = C(0xFF000000), TertiaryContainer = C(0xFFC8C58E), OnTertiaryContainer = C(0xFF0C0C00),
            Error = C(0xFFFFECE9), OnError = C(0xFF000000), ErrorContainer = C(0xFFFFAEA4), OnErrorContainer = C(0xFF220001),
            Background = C(0xFF1A120D), OnBackground = C(0xFFF0DFD7), Surface = C(0xFF1A120D), OnSurface = C(0xFFFFFFFF),
            SurfaceVariant = C(0xFF52443C), OnSurfaceVariant = C(0xFFFFFFFF), Outline = C(0xFFFFECE3), OutlineVariant = C(0xFFD3BFB4),
            Scrim = C(0xFF000000), Shadow = C(0xFF000000),
            InverseSurface = C(0xFFF0DFD7), InverseOnSurface = C(0xFF000000), InversePrimary = C(0xFF703912),
            SurfaceDim = C(0xFF1A120D), SurfaceBright = C(0xFF594E48),
            SurfaceContainerLowest = C(0xFF000000), SurfaceContainerLow = C(0xFF271E19), SurfaceContainer = C(0xFF382E29),
            SurfaceContainerHigh = C(0xFF443934), SurfaceContainerHighest = C(0xFF4F453F),
            CustomColor1 = new LMaterialColorFamily(C(0xFFFFEED3), C(0xFF000000), C(0xFFE7BD69), C(0xFF120A00)),
            CustomColor2 = new LMaterialColorFamily(C(0xFFDDFAAE), C(0xFF000000), C(0xFFB0CC84), C(0xFF060E00)),
        };
    }
}
